#!/usr/bin/python
# this is a config for tutorial
{
    'is_dry_run': False,

    'dir1': '1',
    'dir2': '2',
    'dir3': '3',

    'a very long path blah blah': 'file_path_______________1',
    'another very long path blah blah': 'file_path_______________2',
    'yet another very long path blah blah': 'file_path_______________3',
}